# Generated by Django 5.1.7 on 2026-03-31 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='Identifier for the type of action (e.g., DOCUMENT_UPLOADED)', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Additional metadata related to the action (e.g., document ID, search terms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(help_text='The organization context for this action', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.organization')),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_audit_organiz_c1c99d_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx')],
            },
        ),
    ]
