# Generated by Django 5.1.7 on 2026-04-02 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization context for this action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.organization'),
        ),
    ]
